### ISSUE TITLE
Implement the tree structure for terrains

### ISSUE THREAD

**Issue by gullcomb** [blendit/env#1]
First implementation step: be able to compute the height at any position.

**Comment by coma94** [comment]
@gullcomb It seems to be possible to have more than 1 object with intersection mode Replace.
If we only have 1 background and 2 replacing the background at different positions, for example.. No ?

**Comment by coma94** [comment]
Just need some tests now.

**Comment by coma94** [comment]
Problem: when create a child of ReplaceNode, when the background is directly a Feature.  
Solution: convert _all_ features as nodes before adding them to the tree.

**Comment by coma94** [comment]
Done.
