### ISSUE TITLE
Reorganize all files so it's not a mess anymore

### ISSUE THREAD

**Issue by rmonat** [blendit/env#21]
Example:
- doc/
- src/
- tests/

**Comment by coma94** [comment]
+1

**Comment by coma94** [comment]
What about merges with moving files ?

Moreover, with your proposition it will be hard ton import the code in the tests, because it imports the src/ classes..  
It seems hard to put test_ files out of src/ dir.

**Comment by rmonat** [comment]
Well, try the branch feature-021:
When you are in the env repository, just launch: python3 -m unittest discover 
Or if you want something a bit more precise: python3 -m tests.test_feature_tree

**Comment by coma94** [comment]
Oh yes I see !

What about the merge of existing things ?
Maybe do quickly the reorganization _now_, starting from master, while there are no other branches open.

**Comment by coma94** [comment]
Done.
Bonus: good usage of coveralls.
