### ISSUE TITLE
Blender GUI

### ISSUE THREAD

**Issue by coma94** [blendit/env#36]
Graphical interface for Blender.

We need:
- A basic interface for setting a plane as "world"
- The possibility of adding objects to this world: rivers, roads, mountains, ...
- Editing of these objects. 
- Generating the final heightmap & models

Problems:
- How to show and modify these objects into Blender ?
  --> Maybe create an **external** interface for drawing the zones, then create a file, which we import into blender, adding heightmap and all the models.

**Comment by coma94** [comment]
@rmonat: critical for the design of #18

**Comment by rmonat** [comment]
(less critical) How to apply a UV texture to an imported model?

**Comment by rmonat** [comment]
Real interface with the feature_tree:
- Need to import in blender an environment (at least feature tree) and not just a heightmap
- Be able to construct an environment through a CLI or a GUI

**Comment by coma94** [comment]
GUI now:
- button for choosing a Environment file (pickle ?) (almost done)

**Comment by rmonat** [comment]
But, what is in Env ? Right now, a feature tree, and after, a feature tree but also models etc ?

**Comment by rmonat** [comment]
Moreover, HeightMap and Feature Tree are not linked right now ?

**Comment by coma94** [comment]
Done & merged.
