### ISSUE TITLE
Install required packages into blender

### ISSUE THREAD

**Issue by coma94** [blendit/env#45]
In #18 : find a way to automatically install python packages into blender.

**Comment by rmonat** [comment]
http://blender.stackexchange.com/questions/5287/using-3rd-party-python-modules

**Comment by rmonat** [comment]
It looks like the following does not work (missing Python.h headers, altough python*-dev installed)

``` PY_BLEND=/tmp/blender-2.77-linux-glibc211-x86_64/2.77/python/
cp -a /usr/lib/python3.4/distutils ${PY_BLEND}/lib/python3.5/ # idem

wget https://bootstrap.pypa.io/get-pip.py -O /tmp/get-pip.py
PYTHON=${PY_BLEND}/bin/python3.5m # changer selon la version de blender...
${PYTHON} /tmp/get-pip.py --user

${PYTHON} -m pip install --user shapely pillow
```

**Comment by rmonat** [comment]
@coma94 if you have some time, could you try the script to confirm it does not work ?

**Comment by coma94** [comment]
Maybe done ? (if packages are installed for the "system python distribution").

**Comment by coma94** [comment]
Done.
