### ISSUE TITLE
Improving shapes 

### ISSUE THREAD

**Issue by rmonat** [blendit/env#55]
In the vegetation class, in src/landscape.py, there are no defined shape. This create a big issue for all the feature_tree I guess. 

From my point of view, this also embarrassing to "link" this class with Blender. It would be _WAY_ simpler, if in the init the shape was provided with a Polygon from shapely, as decided when designing the whole system.

Concerning the possible issues:
- shapely can compute the centroid of a polygon
- it can also compute a bounding_box
- to place a tree in the polygon, this should be ok: pick a tree position at random in the bounding box. If it is in the polygon (ask shapely), then we are done. Otherwise, pick another position at random. It should converge quite quickly.

**Comment by coma94** [comment]
Also to do:
- Solve a bug in tests 
- do not plot trees when a replace feature overlap the forest (typically a road)

**Comment by coma94** [comment]
Pushed eda51e1 on master by mistake. @rmonat can you check that everything is ok ?
