### ISSUE TITLE
Linking Vegetation with grease_pencil.py

### ISSUE THREAD

**Issue by rmonat** [blendit/env#58]
Interface with Blender

**Comment by coma94** [comment]
Bug with coordinates.

**Comment by coma94** [comment]
@rmonat Possible to add some parameters on vegetation ? Like number of trees and size.

**Comment by rmonat** [comment]
I'll do that

**Comment by coma94** [comment]
Option for vegetation:
- Number of models
- Path to the model
- Size of the model (possible to modify it after creating env: see what I've done in interface.py)
