### ISSUE TITLE
Models translation is bad 

### ISSUE THREAD

**Issue by rmonat** [blendit/env#61]
En gros ce que je fais dans grease_pencil c'est que :
1) Je prends les coordonnées blender et je les multiplies par 5, -5
2) Je trouve le rectangle contenant toutes les formes, et son coin bas gauche
3) Je translate toutes les formes du coin bas gauche
4) Je lance Env la dessus
5) Je resize ensuite

Bugs:
Par exemple faire un triangle de végétation. Les arbres ne seront pas au bon endroit mais auront la bonne forme (cf MountainImg, où la montagne est pile à la place du polygone dessiné)

Faire deux triangles de végétation dans x < 0, y < 0 et x < 0, y > 0. Regarder ce qu'il se passe

**Comment by coma94** [comment]
Related to #58

**Comment by coma94** [comment]
Still a little translation problem with vegetation.

Trees seems to have a little shift, maybe in Env they are not at the right place, event if they are in Blender.
